[package]
name = "hjaltes-widgets"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
futures-timer = "3"
image = "0.25"
dbus = "0.9"
dbus-crossroads = "0.5"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.ori]
# git = "https://github.com/ori-ui/ori"
# branch = "rewrite"

path = "../ori/crates/ori-gtk4"

package = "ori-gtk4"
features = ["image", "adwaita", "layer-shell"]
